# CI de Nível 02 - Disparo agendado

# nome do nosso 'pipeline'
name: 'Execução agendada'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  schedule:
    - cron: '0 6 * * 0'

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    #maquina que o jobe vai executar
    runs-on: ubuntu-latest

    # passos do script de buil
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependenscias
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright  install

      # Executando  os teste e2e
      - name: Executando Testes E2E
        run: yarn run e2e
