# CI de Nível 03 - Disparo manual após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # Condicional: executa somente se o workflow anterior teve sucesso
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # máquina que o job vai usar
    runs-on: ubuntu-latest

    # passos do script de build/teste
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das dependências 
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # Executando os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      # Upload do relatório
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with: 
          name: relatorio
          path: ./playwright-report
